# This is a basic workflow to help you get started with Actions

name: temp

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "backtrace" branch
  push:
    branches: [ "cmake-temp" ]
  pull_request:
    branches: [ "cmake-temp" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        # supported are: armeabi-v7a, arm64-v8a, x86_64. x86 (32-bit) is NOT supported
        abi: [armeabi-v7a]
        # 64 bit architectures will always have min API level 21 https://stackoverflow.com/a/56467008
        apiLevel: [16]
        ndk: 21.4.7075529

    steps:
      # Install latest CMake.
      - uses: lukka/get-cmake@latest
      
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Install curl headers
        run: sudo apt-get install -y libcurl4-openssl-dev

      - name: CMake
        run: |
          env
          ls -lsa $ANDROID_HOME/ndk/
          mkdir cbuild 
          cmake -S . -B cbuild/ -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk/${{ matrix.ndk }}/build/cmake/android.toolchain.cmake -DANDROID_ABI=${{ matrix.abi }} -DANDROID_PLATFORM=${{ matrix.apiLevel }} -DANDROID_NATIVE_API_LEVEL=${{ matrix.apiLevel }} -DANDROID_TOOLCHAIN=clang
          cmake --build cbuild/ 
